#!/bin/bash

unset DIRTY
tracked_dirty=()
while IFS= read -r record; do
    [[ -n "$record" ]] || continue
    tracked_dirty+=("${record:3}")
done < <(git status --porcelain=v1 --untracked-files=no)

if [[ ${#tracked_dirty[@]} -gt 0 ]]; then
    release_transform_only=false
    if [[ ${DRONE_TAG:-} == "v1.0" && ${DRONE_BRANCH:-} == "layersentry-v1.0-dev" ]]; then
        mapfile -t normalized_dirty < <(printf '%s\n' "${tracked_dirty[@]}" | sort -u)
        expected_dirty=(
            "pkg/console/install_panels.go"
            "pkg/console/util.go"
        )
        if [[ ${#normalized_dirty[@]} -eq ${#expected_dirty[@]} ]]; then
            release_transform_only=true
            for index in "${!expected_dirty[@]}"; do
                if [[ ${normalized_dirty[$index]} != "${expected_dirty[$index]}" ]]; then
                    release_transform_only=false
                    break
                fi
            done
        fi
    fi

    if [[ $release_transform_only == true ]]; then
        echo "LayerSentry release version gate: accepting only deterministic installer UX transform dirtiness"
    else
        DIRTY="-dirty"
    fi
fi

COMMIT=$(git rev-parse --short HEAD)
VERSION=${DRONE_TAG:-${DRONE_BRANCH}}
VERSION=${VERSION:-"master"}

if [[ -n "$DIRTY" ]]; then
    VERSION="${COMMIT}${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

echo "DRONE_BUILD_EVENT:" $DRONE_BUILD_EVENT
if [ "$DRONE_BUILD_EVENT" == "cron" ]; then
  echo "build install qcow image on cronjob"
  BUILD_QCOW="true"
fi
